# GENERATED by Tests/Pickle/New-LabelFeatures.py from the Defs and the French DefInjected files. Do not edit by hand.
# Each step names the def type (the moa is a ThingDef and a PawnKindDef of one name). Tool labels are asserted by
# 02 in the language of the pass. A text still in the other language here is a translation the game did not apply.
# The English source is the Def value itself, there is no English language folder. Played in the English pass.
@en-only
Feature: the English texts reach the loaded definitions

  Scenario: the texts a player reads
    Given Moa Renew: the game has finished starting
    And the main menu is open
    Then Moa Renew: the PawnKindDef "Moa" reads "label" as "moa"
    Then Moa Renew: the ThingDef "EggMoaFertilized" reads "description" as "A fertilized moa egg. If all goes well, it should hatch into a baby moa. It can be eaten raw, but it's much better cooked."
    Then Moa Renew: the ThingDef "EggMoaFertilized" reads "label" as "moa egg (fert.)"
    Then Moa Renew: the ThingDef "EggMoaUnfertilized" reads "description" as "An unfertilized moa egg. It can be eaten raw, but it's much, much better cooked."
    Then Moa Renew: the ThingDef "EggMoaUnfertilized" reads "label" as "moa egg (unfert.)"
    Then Moa Renew: the ThingDef "Moa" reads "description" as "A large flightless bird native to the planet of Reach, known for its tasty meat. It has been long domesticated, but also lives in the wild."
    Then Moa Renew: the ThingDef "Moa" reads "label" as "moa"
    Then Moa Renew: the ThingDef "Moa" reads "race.meatLabel" as "moa meat"
