# GENERATED by Tests/Pickle/New-LabelFeatures.py from the Defs and the French DefInjected files. Do not edit by hand.
# Each step names the def type (the moa is a ThingDef and a PawnKindDef of one name). Tool labels are asserted by
# 02 in the language of the pass. A text still in the other language here is a translation the game did not apply.
# Played in the French pass (-Language French); developer mode shows an accented fallback for a missing key.
@fr-only
Feature: the French texts reach the loaded definitions

  Scenario: the texts a player reads
    Given Moa Renew: the game has finished starting
    And the main menu is open
    Then Moa Renew: the PawnKindDef "Moa" reads "label" as "moa"
    Then Moa Renew: the ThingDef "EggMoaFertilized" reads "description" as "Un œuf de moa fécondé. Si tout se passe bien, un petit moa devrait en sortir. Il peut être mangé cru, mais il est bien meilleur une fois cuit."
    Then Moa Renew: the ThingDef "EggMoaFertilized" reads "label" as "œuf de moa (fécondé)"
    Then Moa Renew: the ThingDef "EggMoaUnfertilized" reads "description" as "Un œuf de moa non fécondé. Il peut être mangé cru, mais il est bien meilleur une fois cuit."
    Then Moa Renew: the ThingDef "EggMoaUnfertilized" reads "label" as "œuf de moa (non fécondé)"
    Then Moa Renew: the ThingDef "Moa" reads "description" as "Un grand oiseau incapable de voler, originaire de la planète Reach et réputé pour sa viande savoureuse. Domestiqué depuis longtemps, il vit également à l'état sauvage."
    Then Moa Renew: the ThingDef "Moa" reads "label" as "moa"
    Then Moa Renew: the ThingDef "Moa" reads "race.meatLabel" as "viande de moa"

  Scenario: the tools a player reads in a fight
    Given Moa Renew: the game has finished starting
    And the main menu is open
    Then Moa Renew: the ThingDef "Moa" has a tool labelled "bec"
    Then Moa Renew: the ThingDef "Moa" has a tool labelled "griffes"
    Then Moa Renew: the ThingDef "Moa" has a tool labelled "tête"
