"""Generates 08-labels-en and 09-labels-fr from the Defs and the DefInjected files. Run:
uv run python Tests/Pickle/New-LabelFeatures.py"""
import xml.etree.ElementTree as ET
from pathlib import Path
root = Path(__file__).resolve().parents[2]
mod = root / 'Mod'
en = {}
for f in (mod / 'Defs').glob('*.xml'):
    for d in ET.parse(f).getroot():
        n = d.findtext('defName')
        for fld in ('label', 'description'):
            v = d.findtext(fld)
            if v is not None:
                en[(d.tag, n, fld)] = v
        v = d.findtext('race/meatLabel')
        if v is not None:
            en[(d.tag, n, 'race.meatLabel')] = v
fr = {}
for f in (mod / 'Languages/French/DefInjected').rglob('*.xml'):
    kind = f.parent.name
    for e in ET.parse(f).getroot():
        n, _, rest = e.tag.partition('.')
        fr[(kind, n, rest)] = e.text
def line(kind, name, path, value):
    return f'    Then Moa Renew: the {kind} "{name}" reads "{path}" as "{value}"'
def gen(tag, title, src, header):
    lines = [header, tag, f'Feature: {title}', '', '  Scenario: the texts a player reads',
             '    Given Moa Renew: the game has finished starting', '    And the main menu is open']
    for (kind, n, path), v in sorted(src.items()):
        if path.startswith('tools.'):
            continue
        lines.append(line(kind, n, path, v))
    if tag == '@fr-only':
        lines += ['', '  Scenario: the tools a player reads in a fight', '    Given Moa Renew: the game has finished starting', '    And the main menu is open']
        for k, v in sorted(src.items()):
            if k[2].startswith('tools.') and k[2].endswith('.label'):
                lines.append(f'    Then Moa Renew: the ThingDef "{k[1]}" has a tool labelled "{v}"')
    lines.append('')
    return '\n'.join(lines)
feat = root / 'Tests/Pickle/Mod/Pickle/Features'
common = ('# GENERATED by Tests/Pickle/New-LabelFeatures.py from the Defs and the French DefInjected files. Do not edit by hand.\n'
          '# Each step names the def type (the moa is a ThingDef and a PawnKindDef of one name). Tool labels are asserted by\n'
          '# 02 in the language of the pass. A text still in the other language here is a translation the game did not apply.\n')
(feat / '08-labels-en.feature').write_text(gen('@en-only', 'the English texts reach the loaded definitions', en, common + '# The English source is the Def value itself, there is no English language folder. Played in the English pass.'), encoding='utf-8')
(feat / '09-labels-fr.feature').write_text(gen('@fr-only', 'the French texts reach the loaded definitions', fr, common + '# Played in the French pass (-Language French); developer mode shows an accented fallback for a missing key.'), encoding='utf-8')
print(len(en), len(fr))
